stages:
  - docker
  - checkout
  - test

variables:
  BITBAKE_IMAGE: ${CI_REGISTRY_IMAGE}:ci-${CI_COMMIT_REF_SLUG}-bitbake
  BITBAKE_CHECKOUT_IMAGE: ${CI_REGISTRY_IMAGE}:ci-${CI_COMMIT_REF_SLUG}-checkout

include:
  - local: "scripts/ci/gitlab/docker.yml"
  - local: "scripts/ci/gitlab/checkout.yml"
  - local: "scripts/ci/gitlab/tests.yml"

Docker setup:
  extends: .bb_docker_local

  stage: docker
  variables:
    BITBKAE_IMAGE_MASTER: ${CI_REGISTRY_IMAGE}:ci-master-bitbake
    BITBAKE_CHECKOUT_IMAGE_MASTER: ${CI_REGISTRY_IMAGE}:ci-master-checkout
  except:
    - pushes

Checkout:
  extends: .bb_checkout

  stage: checkout
  variables:
    MANIFEST: master
    CURRENT_PROJECT: meta-updater
  except:
    - pushes

Build core-image-minimal:
  extends: .bitbake

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-core-image-minimal'
    BITBAKE_TARGETS: 'core-image-minimal'
  artifacts:
    name: "core-image-minimal_$CI_COMMIT_REF_SLUG"
    paths:
      - $TEST_BUILD_DIR/tmp/deploy/images/*/core-image-minimal*
  except:
    - pushes

Build core-image-minimal (rpi):
  extends: .bitbake

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-core-image-minimal-rpi'
    BITBAKE_TARGETS: 'core-image-minimal'
    TEST_MACHINE: 'raspberrypi3'
  artifacts:
    name: "core-image-minimal-rpi_$CI_COMMIT_REF_SLUG"
    paths:
      - $TEST_BUILD_DIR/tmp/deploy/images/*/core-image-minimal*
  except:
    - pushes

Oe-selftest qemux86_64:
  extends: .oe-selftest

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-oe-qemux86_64'
    OE_SELFTESTS: 'updater_native updater_qemux86_64'
  except:
    - pushes

# Not run by default, triggered on nightlies

Oe-selftest minnowboard:
  extends: .oe-selftest

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-oe-minnowboard'
    OE_SELFTESTS: 'updater_minnowboard'
  except:
    - pushes
  only:
    variables:
      - $OE_MINNOWBOARD

Oe-selftest rpi:
  extends: .oe-selftest

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-oe-rpi'
    OE_SELFTESTS: 'updater_raspberrypi'
  except:
    - pushes
  only:
    variables:
      - $OE_RPI

Ptest qemux86_64:
  extends: .oe-selftest

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-oe-qemux86_64-ptest'
    OE_SELFTESTS: 'updater_qemux86_64_ptest'
  except:
    - pushes
  only:
    variables:
      - $OE_PTEST
